name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 44 hours
    - cron: "20 * * * *"
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      #- uses: vn7n24fzkq/github-profile-summary-cards@release
      # - uses: m1xzg/github-profile-summary-cards@release
      - uses: m1xzg/github-profile-summary-cards@m1xzg-v1
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, default to main, branch name to push cards
          BRANCH_NAME: "main"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 0
          # EXCLUDE is an optional comma seperated list of languages to exclude, defaults to ""
          EXCLUDE: ""
          # AUTO_PUSH is optional, a boolean variable default to true, whether automatically push generated files to desired branch 
          AUTO_PUSH: false
      
      # Keep only the aura and aura_dark themes and remove all others
      - name: Keep only aura themes
        run: |
          cd profile-summary-card-output
          find . -mindepth 1 -maxdepth 1 -type d ! -name 'aura' ! -name 'aura_dark' -exec rm -rf {} +
          
      # Commit and push changes
      - name: Commit changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_GH_PAT }}@github.com/${{ github.repository }}.git
          git config --global user.email "rmckenzi@rpmdp.com"
          git config --global user.name "Robert McKenzie"
          git add profile-summary-card-output
          git commit -m "Generate profile summary cards (aura themes only)" || echo "No changes to commit"
          git push
